### ISSUE TITLE
Incorrect Character Encoding

### ISSUE THREAD

**Issue by europ** [kabell/fi-muni-drill#1]
Platform:
* Mozilla Firefox 66.0.4
* Ubuntu 16.04.6 LTS

URL: https://kabell.sk/fi_muni_drill/question/PV157/185

![image](https://user-images.githubusercontent.com/22373707/57640625-565c5c00-75b3-11e9-9f52-f532c1fe8e18.png)

**Comment by kabell** [comment]
Fixed.
